### ISSUE TITLE
Update documentation with perfomance tuning settings

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/prometheus_bigquery_remote_storage_adapter#21]
##  What happens?

High utilization can cause write errors with the default settings.

## What were you expecting to happen?

Provide some guidance on CPU/Memory settings, in addition to sensible `queue_config` settings.
Provide guidance for the BQ timeout setting.

**Comment by robklg** [comment]
Hi, we're in the process of setting up your remote storage adapter. And I was precisely looking for some guidance on the tuning part. Our Prometheus cluster seems to completely overwhelm the adaptor, which we've set up running as a separate pod. Any idea when you'll come around to documenting this part?

**Comment by Smiley73** [comment]
@robklg not sure when we get to it, so here's a quick and dirty reply that should get you going.

We found prometheus to the storage adapter is one constraint, but also the amount of data we sent to BigQuery. We do set a fairly large CPU request and limit, depending on which system we're running on. We also tweaked the write queue config on the prometheus side. It's also important to decide which metrics to store long-term. It doesn't make sense to store everything. Before we started getting selective, BQ was choking on the amount of data (which was insanely high in our case).

Below is an example config that needs to go into `prometheus.yml`. You'll have to tweak it for your needs.
```
remote_write:
- url: http://localhost:9201/write
  remote_timeout: 2m
  write_relabel_configs:
  - source_labels: [__name__]
    separator: ;
    regex: ALERTS|apiserver_request_.*|kube_namespace_labels
    replacement: $1
    action: keep
  queue_config:
    capacity: 500
    max_shards: 200
    min_shards: 1
    max_samples_per_send: 100
    batch_send_deadline: 5s
    min_backoff: 30ms
    max_backoff: 100ms
remote_read:
- url: http://localhost:9201/read
  remote_timeout: 1m
```
