### ISSUE TITLE
Add sample k8s configuration

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/prometheus_bigquery_remote_storage_adapter#6]
## What happens?
A user currently has to figure out how to add this to their own k8s configuation.

## What were you expecting to happen?

We provide an example that can simply be copied. This should be a sidecar to the prometheus container itself, to keep cross-node network communication at a minimum.

**Comment by blerest** [comment]
That would be really useful. Do you have something to share?

**Comment by Smiley73** [comment]
@blerest here's quick and dirty (sanitized) copy'n'paste. We're running prometheus as a stateful set. The pod consists of a prometheus and a storage adapter container. We also use a secrets engine to store the json file, then mount it through an init container. CPU and memory requirements will heavily depend on how much data your pumping through. Here are the parts that matter, add this to your own statefulset yaml for prometheus:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: your-namespace
  name: your-prometheus
spec:
  template:
    spec:
      containers:
        - name: "prometheus-storage-bigquery"
          image: "<registry-url>/prometheus_bigquery_remote_storage_adapter:v0.4.3"
          env:
            - name: PROMBQ_GCP_JSON
              value: "/var/lib/mysecrets/super_secret.json"
            - name: PROMBQ_DATASET
              value: "prometheus"
            - name: PROMBQ_TABLE
              value: "metrics"
            - name: PROMBQ_TIMEOUT
              value: "2m"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "5"
              memory: "500Mi"
            requests:
              cpu: "5"
              memory: "500Mi"
          volumeMounts:
            - name: secrets
              mountPath: /var/lib/mysecrets
```

**Comment by soggiest** [comment]
We're trying out this storage adapter in our K8s environment and I found I had to include this to our deployment spec. 

```
      securityContext:
        allowPrivilegeEscalation: false
        # User 65532 is the distroless nonroot user ID
        runAsUser: 65532
```

Great job on this app!
